//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omikron.VaultService.UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Omikron.VaultService.UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;status&quot;: &quot;success&quot;,
        ///  &quot;postcode&quot;: &quot;W14 9JH&quot;,
        ///  &quot;postcode_type&quot;: &quot;full&quot;,
        ///  &quot;url&quot;: &quot;https://propertydata.co.uk/draw?input=W14+9JH&quot;,
        ///  &quot;bedrooms&quot;: 2,
        ///  &quot;data&quot;: {
        ///    &quot;points_analysed&quot;: 20,
        ///    &quot;radius&quot;: &quot;0.14&quot;,
        ///    &quot;average&quot;: 602345,
        ///    &quot;70pc_range&quot;: [
        ///      550000,
        ///      685000
        ///    ],
        ///    &quot;80pc_range&quot;: [
        ///      535000,
        ///      725000
        ///    ],
        ///    &quot;90pc_range&quot;: [
        ///      500000,
        ///      750000
        ///    ],
        ///    &quot;100pc_range&quot;: [
        ///      495000,
        ///      799000
        ///    ],
        ///    &quot;raw_data&quot;: []
        ///  },
        ///  &quot;proc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PropertyDataSuccessJSON {
            get {
                return ResourceManager.GetString("PropertyDataSuccessJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;BillingAccount&quot;: {
        ///&quot;AccountType&quot;: &quot;Trial&quot;,
        ///&quot;AccountBalance&quot;: 999.99,
        ///&quot;TransactionCost&quot;: 999.99,
        ///&quot;ExtraInformation&quot;: {}
        ///},
        ///&quot;TechnicalSupport&quot;: {
        ///&quot;ServerId&quot;: &quot;UK1&quot;,
        ///&quot;RequestId&quot;: &quot;d7a65e4892c6405cabd94cae48ca04ca&quot;,
        ///&quot;QueryDurationMs&quot;: 1,
        ///&quot;SupportDate&quot;: &quot;30/09/2021&quot;,
        ///&quot;SupportTime&quot;: &quot;14:08:38&quot;,
        ///&quot;SupportCode&quot;: &quot;d7a65e48&quot;,
        ///&quot;SupportInformationList&quot;: []
        ///},
        ///&quot;Request&quot;: {
        ///&quot;RequestGuid&quot;: &quot;d7a65e48-92c6-405c-abd9-4cae48ca04ca&quot;,
        ///&quot;PackageId&quot;: &quot;513c6298-a270-4c92-a9d6-1aa51e2b6f72&quot;,
        ///&quot;PackageVersion&quot;: 2, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UkVehicleDataFailureJSON {
            get {
                return ResourceManager.GetString("UkVehicleDataFailureJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;BillingAccount&quot;: {
        ///&quot;AccountType&quot;: &quot;Trial&quot;,
        ///&quot;AccountBalance&quot;: 999.99,
        ///&quot;TransactionCost&quot;: 999.99,
        ///&quot;ExtraInformation&quot;: {}
        ///},
        ///&quot;TechnicalSupport&quot;: {
        ///&quot;ServerId&quot;: &quot;UK1&quot;,
        ///&quot;RequestId&quot;: &quot;0f353a7c32e0427ca1c00743bd97bfea&quot;,
        ///&quot;QueryDurationMs&quot;: 137,
        ///&quot;SupportDate&quot;: &quot;30/09/2021&quot;,
        ///&quot;SupportTime&quot;: &quot;14:07:38&quot;,
        ///&quot;SupportCode&quot;: &quot;0f353a7c&quot;,
        ///&quot;SupportInformationList&quot;: [
        ///&quot;B2B-R1&quot;
        ///]
        ///},
        ///&quot;Request&quot;: {
        ///&quot;RequestGuid&quot;: &quot;0f353a7c-32e0-427c-a1c0-0743bd97bfea&quot;,
        ///&quot;PackageId&quot;: &quot;513c6298-a270-4c92-a9d6-1aa51e2b6f72&quot;,
        ///&quot;Packa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UkVehicleDataSuccesJSON {
            get {
                return ResourceManager.GetString("UkVehicleDataSuccesJSON", resourceCulture);
            }
        }
    }
}
