// <auto-generated />
using System;
using Omikron.IdentityService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Omikron.IdentityService.Infrastructure.Data.Migrations.IdentityServer.IdentityDb
{
    [DbContext(typeof(OmikronIdentityDbContext))]
    [Migration("20190815092640_AssignedPermissions")]
    partial class AssignedPermissions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("usm")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.ConfirmationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Expiration");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("Type");

                    b.Property<int>("UserId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfirmationTokens");
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("Domain");

                    b.Property<Guid>("ExternalId");

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedName")
                        .IsRequired();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 8, 15, 9, 26, 39, 617, DateTimeKind.Utc).AddTicks(1143),
                            Description = "Ability to see a page with a list of tenants alongside with search functionality",
                            Domain = 1,
                            ExternalId = new Guid("18bb49e7-69ed-47bd-bfc6-5372dd15315a"),
                            Name = "Search.Tenants",
                            NormalizedName = "Search.Tenants"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 8, 15, 9, 26, 39, 617, DateTimeKind.Utc).AddTicks(4366),
                            Description = "Ability to see button for add tenant alongside with ability to create tenant",
                            Domain = 1,
                            ExternalId = new Guid("9feb92a5-398f-4069-8f5f-6da5212af3f2"),
                            Name = "Add.Tenant",
                            NormalizedName = "Add.Tenant"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 8, 15, 9, 26, 39, 617, DateTimeKind.Utc).AddTicks(4512),
                            Description = "Ability to navigate to tenant details page and edit tenant",
                            Domain = 1,
                            ExternalId = new Guid("cba862dc-fd5f-4c70-84a6-3fb16cb868e1"),
                            Name = "Edit.Tenant",
                            NormalizedName = "Edit.Tenant"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 8, 15, 9, 26, 39, 617, DateTimeKind.Utc).AddTicks(4518),
                            Description = "Ability to navigate to tenant details page without ability to edit tenant",
                            Domain = 1,
                            ExternalId = new Guid("865dd083-5872-406a-bf8b-bd440f31d6fe"),
                            Name = "Read.Tenant",
                            NormalizedName = "Read.Tenant"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 8, 15, 9, 26, 39, 617, DateTimeKind.Utc).AddTicks(4522),
                            Description = "Ability to see delete action alongside with ability to delete tenant",
                            Domain = 1,
                            ExternalId = new Guid("e445a667-0a50-470f-84d5-84959adca363"),
                            Name = "Delete.Tenant",
                            NormalizedName = "Delete.Tenant"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 8, 15, 9, 26, 39, 617, DateTimeKind.Utc).AddTicks(4528),
                            Description = "Ability to see a page with a list of users alongside with search functionality",
                            Domain = 2,
                            ExternalId = new Guid("8d5e1370-d20c-4e2e-9a93-84f5d4e620c4"),
                            Name = "Search.Users",
                            NormalizedName = "Search.Users"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 8, 15, 9, 26, 39, 617, DateTimeKind.Utc).AddTicks(4532),
                            Description = "Ability to see button for add user alongside with ability to create user",
                            Domain = 2,
                            ExternalId = new Guid("0ebcb068-fe5b-4696-9392-eca13615139c"),
                            Name = "Add.User",
                            NormalizedName = "Add.User"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 8, 15, 9, 26, 39, 617, DateTimeKind.Utc).AddTicks(4535),
                            Description = "Ability to navigate to user details page and edit user",
                            Domain = 2,
                            ExternalId = new Guid("9c0d6b32-6f5f-41a3-8336-43f33dd61477"),
                            Name = "Edit.User",
                            NormalizedName = "Edit.User"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 8, 15, 9, 26, 39, 617, DateTimeKind.Utc).AddTicks(4540),
                            Description = "Ability to see delete action alongside with ability to delete user",
                            Domain = 2,
                            ExternalId = new Guid("d686c12f-8ac8-4214-a1a2-e8b7d02b18ad"),
                            Name = "Delete.User",
                            NormalizedName = "Delete.User"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 8, 15, 9, 26, 39, 617, DateTimeKind.Utc).AddTicks(4545),
                            Description = "Ability to navigate to user details page without ability to edit user",
                            Domain = 2,
                            ExternalId = new Guid("57c57548-266d-4cd3-a35e-de256c6cedd8"),
                            Name = "Read.User",
                            NormalizedName = "Read.User"
                        });
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<Guid>("ExternalId");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "aad7b7be72bf42ea8f994c2d460088ae",
                            ExternalId = new Guid("05a075a5-076a-465c-811d-0f5c875e9b3f"),
                            Name = "Tenant.Administrator",
                            NormalizedName = "Tenant.Administrator"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "b953e152e59a40348608d82792882b5d",
                            ExternalId = new Guid("4e313f82-5801-41ec-b147-86697f85fccf"),
                            Name = "System.Tenant.Administrator",
                            NormalizedName = "System.Tenant.Administrator"
                        });
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.RolePermission", b =>
                {
                    b.Property<int>("PermissionId");

                    b.Property<int>("RoleId");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 10,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<int>("AccountStatus");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<Guid>("ExternalId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(550);

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Finbuckle.MultiTenant.MultiTenantIdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Finbuckle.MultiTenant.MultiTenantIdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Finbuckle.MultiTenant.MultiTenantIdentityUserLogin<int>", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LoginProvider")
                        .IsRequired();

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("ProviderKey")
                        .IsRequired();

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LoginProvider", "ProviderKey", "TenantId")
                        .IsUnique();

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Finbuckle.MultiTenant.MultiTenantIdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Finbuckle.MultiTenant.MultiTenantIdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.ConfirmationToken", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.User", "User")
                        .WithMany("ConfirmationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.RolePermission", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.Permission", "Permission")
                        .WithMany("AssignedRoles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.Role", "Role")
                        .WithMany("AssignedPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Finbuckle.MultiTenant.MultiTenantIdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Finbuckle.MultiTenant.MultiTenantIdentityUserClaim<int>", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Finbuckle.MultiTenant.MultiTenantIdentityUserLogin<int>", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Finbuckle.MultiTenant.MultiTenantIdentityUserRole<int>", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Finbuckle.MultiTenant.MultiTenantIdentityUserToken<int>", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
