// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Omikron.IdentityService.Infrastructure;

namespace Omikron.IdentityService.Infrastructure.Data.Migrations.IdentityServer.IdentityDb
{
    [DbContext(typeof(OmikronIdentityDbContext))]
    [Migration("20210722114147_PhoneNumberSeedData")]
    partial class PhoneNumberSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("usm")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.ConfirmationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfirmationTokens");

                    b
                        .HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Domain")
                        .HasColumnType("int");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 649, DateTimeKind.Utc).AddTicks(9587),
                            Description = "Ability to see a page with a list of tenants alongside with search functionality.",
                            Domain = 1,
                            ExternalId = new Guid("18bb49e7-69ed-47bd-bfc6-5372dd15315a"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 649, DateTimeKind.Utc).AddTicks(9607),
                            Name = "Search.Tenants",
                            NormalizedName = "SEARCH.TENANTS"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2343),
                            Description = "Ability to see button for add tenant alongside with ability to create tenant. Required Permissions: Search.Tenants",
                            Domain = 1,
                            ExternalId = new Guid("9feb92a5-398f-4069-8f5f-6da5212af3f2"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2345),
                            Name = "Add.Tenant",
                            NormalizedName = "ADD.TENANT"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2359),
                            Description = "Ability to navigate to tenant details page and edit tenant. Required Permissions: Search.Tenants",
                            Domain = 1,
                            ExternalId = new Guid("cba862dc-fd5f-4c70-84a6-3fb16cb868e1"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2360),
                            Name = "Edit.Tenant",
                            NormalizedName = "EDIT.TENANT"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2364),
                            Description = "Ability to navigate to tenant details page without ability to edit tenant. Required Permissions: Search.Tenants",
                            Domain = 1,
                            ExternalId = new Guid("865dd083-5872-406a-bf8b-bd440f31d6fe"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2365),
                            Name = "Read.Tenant",
                            NormalizedName = "READ.TENANT"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2369),
                            Description = "Ability to see delete action alongside with ability to delete tenant. Required Permissions: Search.Tenants, Edit.Tenant",
                            Domain = 1,
                            ExternalId = new Guid("e445a667-0a50-470f-84d5-84959adca363"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2370),
                            Name = "Delete.Tenant",
                            NormalizedName = "DELETE.TENANT"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2380),
                            Description = "Ability to see a page with a list of users alongside with search functionality.",
                            Domain = 2,
                            ExternalId = new Guid("8d5e1370-d20c-4e2e-9a93-84f5d4e620c4"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2380),
                            Name = "Search.Users",
                            NormalizedName = "SEARCH.USERS"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2385),
                            Description = "Ability to see button for add user alongside with ability to create user. Required Permissions: Search.Users",
                            Domain = 2,
                            ExternalId = new Guid("0ebcb068-fe5b-4696-9392-eca13615139c"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2386),
                            Name = "Add.User",
                            NormalizedName = "ADD.USER"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2389),
                            Description = "Ability to navigate to user details page and edit user. Required Permissions: Search.Users",
                            Domain = 2,
                            ExternalId = new Guid("9c0d6b32-6f5f-41a3-8336-43f33dd61477"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2390),
                            Name = "Edit.User",
                            NormalizedName = "EDIT.USER"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2395),
                            Description = "Ability to see delete action alongside with ability to delete user. Required Permissions: Search.Users, Edit.User",
                            Domain = 2,
                            ExternalId = new Guid("d686c12f-8ac8-4214-a1a2-e8b7d02b18ad"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2395),
                            Name = "Delete.User",
                            NormalizedName = "DELETE.USER"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2400),
                            Description = "Ability to navigate to user details page without ability to edit user. Required Permissions: Search.Users",
                            Domain = 2,
                            ExternalId = new Guid("57c57548-266d-4cd3-a35e-de256c6cedd8"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2401),
                            Name = "Read.User",
                            NormalizedName = "READ.USER"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2405),
                            Description = "Ability to see a page with a list of roles alongside with search functionality.",
                            Domain = 3,
                            ExternalId = new Guid("42dc28e4-deca-41bf-960f-f63d4ad41e43"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2406),
                            Name = "Search.Roles",
                            NormalizedName = "SEARCH.ROLES"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2409),
                            Description = "Ability to see button for add role alongside with ability to create role. Required Permissions: Search.Roles",
                            Domain = 3,
                            ExternalId = new Guid("dd37cf7c-da69-4136-8d0b-96f2f40563c4"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2410),
                            Name = "Add.Role",
                            NormalizedName = "ADD.ROLE"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2413),
                            Description = "Ability to navigate to role details page and edit role. Required Permissions: Search.Roles, Edit.Roles",
                            Domain = 3,
                            ExternalId = new Guid("e4cc40f5-2100-497d-8b58-33667376a99a"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2414),
                            Name = "Edit.Role",
                            NormalizedName = "EDIT.ROLE"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2418),
                            Description = "Ability to see delete action alongside with ability to delete role. Required Permissions: Search.Roles, Edit.Roles",
                            Domain = 3,
                            ExternalId = new Guid("426d5137-c41c-4962-a1e0-3fa5c1dbbc45"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2419),
                            Name = "Delete.Role",
                            NormalizedName = "DELETE.ROLE"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2423),
                            Description = "Ability to navigate to role details page without ability to edit role. Required Permissions: Search.Roles",
                            Domain = 3,
                            ExternalId = new Guid("0d6dac73-8728-4d9f-951f-ef4db97c996f"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2424),
                            Name = "Read.Role",
                            NormalizedName = "READ.ROLE"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2427),
                            Description = "Ability to run into interactive view in order to see required permissions for protected parts of the system.",
                            Domain = 3,
                            ExternalId = new Guid("68e3c31c-aade-41d0-88ba-9048e7233b12"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2428),
                            Name = "Interactive.View",
                            NormalizedName = "INTERACTIVE.VIEW"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2432),
                            Description = "Ability to trace data for particular tenant. The permission includes also the ability to see data content what was changed.",
                            Domain = 4,
                            ExternalId = new Guid("77fadd97-22d3-489e-882e-b106f6805bdf"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2433),
                            Name = "Search.DataChangeLogs",
                            NormalizedName = "SEARCH.DATACHANGELOGS"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2438),
                            Description = "Ability to trace data for all tenants. The permission includes also the ability to see data content what was changed.",
                            Domain = 1,
                            ExternalId = new Guid("c5b037e8-1df3-4bc0-92fd-b1cd5c1a1d17"),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 650, DateTimeKind.Utc).AddTicks(2439),
                            Name = "Search.DataChangeLogs.ByTenant",
                            NormalizedName = "SEARCH.DATACHANGELOGS.BYTENANT"
                        });
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.PhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LockoutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Token")
                        .HasColumnType("int");

                    b.Property<DateTime>("TokenCreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TokenExpired")
                        .HasColumnType("bit");

                    b.Property<int>("VerificationAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("[Number] IS NOT NULL");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b84cbc0-8e92-408c-8703-d47da88bcb66"),
                            CreatedAt = new DateTime(2021, 7, 22, 11, 41, 46, 659, DateTimeKind.Utc).AddTicks(8797),
                            LockedOut = false,
                            LockoutTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 7, 22, 11, 41, 46, 659, DateTimeKind.Utc).AddTicks(8809),
                            Number = "+38761000000",
                            Token = 100000,
                            TokenCreationTime = new DateTime(2021, 7, 22, 11, 41, 46, 660, DateTimeKind.Utc).AddTicks(1575),
                            TokenExpired = false,
                            VerificationAttempts = 0,
                            Verified = true
                        });
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "8b8fca96448b4e5c88ee203289305705",
                            Description = "Tenant Administrator Role is a system role and represents the role with the ability to managing users and roles for the tenant. This role cannot be deleted or edit since it's not a user-defined role.",
                            Enabled = true,
                            ExternalId = new Guid("dffa36f1-df2a-419d-9941-a32509a14d69"),
                            Name = "Tenant.Administrator",
                            NormalizedName = "TENANT.ADMINISTRATOR",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "37d78e969dcf4508a062b329fd11a1b8",
                            Description = "System Tenant Administrator Role is a system role and represents the role with the ability to managing tenants users and roles for the main tenant. This role cannot be deleted or edit since it's not a user-defined role.",
                            Enabled = true,
                            ExternalId = new Guid("cb6165cb-4cdf-4fdc-9951-71a9a0485fb9"),
                            Name = "System.Tenant.Administrator",
                            NormalizedName = "SYSTEM.TENANT.ADMINISTRATOR",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "2252384e44dd47c09113604e15c50cee",
                            Description = "Reporting Management is a system role and represents the role with the ability to manage reports. This role cannot be deleted or edit since it's not a user-defined role.",
                            Enabled = true,
                            ExternalId = new Guid("7bfc4797-714b-4fa2-b369-a5c73206800a"),
                            Name = "Reporting.Management",
                            NormalizedName = "REPORTING.MANAGEMENT",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "b9df22d423564666b1cf30fc6ebf4abc",
                            Description = "Omikron user is a default role for Omikron customers.",
                            Enabled = true,
                            ExternalId = new Guid("fc6bd0e0-a573-41cd-87e1-c2be2ca27d7d"),
                            Name = "Omikron.User",
                            NormalizedName = "Omikron.USER",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");

                    b
                        .HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.RolePermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 17,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 18,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 17,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("BudCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BudCustomerSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("PhoneNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumberId")
                        .IsUnique();

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");

                    b
                        .HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.UserLogin", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LoginProvider", "ProviderKey", "TenantId")
                        .IsUnique();

                    b.ToTable("AspNetUserLogins");

                    b
                        .HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b
                        .HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");

                    b
                        .HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.ConfirmationToken", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.User", "User")
                        .WithMany("ConfirmationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.RoleClaim", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.RolePermission", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.Permission", "Permission")
                        .WithMany("AssignedRoles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.Role", "Role")
                        .WithMany("AssignedPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.User", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.PhoneNumber", "PhoneNumberForVerification")
                        .WithOne("Owner")
                        .HasForeignKey("Omikron.IdentityService.Infrastructure.Data.Model.User", "PhoneNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhoneNumberForVerification");
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.UserClaim", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.UserLogin", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.UserRole", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.UserToken", b =>
                {
                    b.HasOne("Omikron.IdentityService.Infrastructure.Data.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.Permission", b =>
                {
                    b.Navigation("AssignedRoles");
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.PhoneNumber", b =>
                {
                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.Role", b =>
                {
                    b.Navigation("AssignedPermissions");
                });

            modelBuilder.Entity("Omikron.IdentityService.Infrastructure.Data.Model.User", b =>
                {
                    b.Navigation("ConfirmationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
